### PR TITLE
Scheduled tests

### PR DESCRIPTION
**Pull request by BrunoLiegiBastonLiegi**
This tries to address #24 by setting up some scheduled tests and build on the first day of each month.

Unfortunately from the [docs](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule):

- This event will only trigger a workflow run if the workflow file is on the default branch.

- Scheduled workflows will only run on the default branch.

Therefore I assume there is no way of testing this out of main.

### CODE REVIEW

**Review by alecandido — APPROVED** [review]

**Comment by alecandido** [comment]
> Therefore I assume there is no way of testing this out of main.

Yes, but the workflow itself is already tested, so it's just about the extra event.

First approximation, just assume that it will work. If it won't, we will fix it (we didn't have it until now, so we're not in a hurry, and it's already proven by the CI the addition is not breaking the existing ones).

If you're unsure about the event itself (cron syntax is a bit cryptic at times), you can use online services like the following:
https://crontab.guru/

**Comment by alecandido** [comment]
(I guess this is not exactly what you wanted)
image

**Comment by BrunoLiegiBastonLiegi** [comment]
> (I guess this is not exactly what you wanted) image 

yeah no this one was just for testing. I'll roll back to the previous one and we will next tuesday whether it worked I guess, unless I change the day...

**Comment by alecandido** [comment]
We should check whether it's possible to rerun pre-commit as with workflows...

**Comment by BrunoLiegiBastonLiegi** [comment]
Yeah indeed, I tried to trigger it again but couldn't manage to find anyway of doing it

**Comment by alecandido** [comment]
pre-commit.ci run

**Comment by alecandido** [comment]
Found!

> **re-running a pull request:** you can trigger a re-run on a pull request by commenting pre-commit.ci run (must appear on a line by itself). alternatively, one can attach a pre-commit.ci run label to the pull request.

https://pre-commit.ci/

**Pull request merged**
